CREATE TABLE TRACKER (id VARCHAR(64) NOT NULL, PRIMARY KEY (id))
CREATE TABLE ADSUSER (id VARCHAR(64) NOT NULL, PRIMARY KEY (id))
CREATE TABLE ADVERTISEMENT (id VARCHAR(64) NOT NULL, PRIMARY KEY (id))
CREATE TABLE VISIT (id VARCHAR(64) NOT NULL, PRIMARY KEY (id))
