CREATE TABLE TRACKER (id VARCHAR(64) NOT NULL, PRIMARY KEY (id))
CREATE TABLE ADSUSER (id VARCHAR(64) NOT NULL, Email VARCHAR(255), FirstName VARCHAR(255), LastName VARCHAR(255), Mobile VARCHAR(255), Password VARCHAR(255), RegisterDate TIMESTAMP, UserType INTEGER, UserStatus INTEGER, VerifyDate TIMESTAMP, PRIMARY KEY (id))
CREATE TABLE ADVERTISEMENT (id VARCHAR(64) NOT NULL, PRIMARY KEY (id))
CREATE TABLE VISIT (id VARCHAR(64) NOT NULL, PRIMARY KEY (id))
