CREATE TABLE TRACKER (id VARCHAR(64) NOT NULL, PRIMARY KEY (id))
CREATE TABLE ADSUSER (Email VARCHAR(255) NOT NULL, FirstName VARCHAR(255), id VARCHAR(64), LastName VARCHAR(255), Mobile VARCHAR(255), Password VARCHAR(255), RegisterDate TIMESTAMP, UserRole INTEGER, UserStatus INTEGER, VerifyDate TIMESTAMP, PRIMARY KEY (Email))
CREATE TABLE ADVERTISEMENT (id VARCHAR(64) NOT NULL, PRIMARY KEY (id))
CREATE TABLE VISIT (id VARCHAR(64) NOT NULL, PRIMARY KEY (id))
